# Generated by Django 3.2.5 on 2021-07-08 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=300)),
                ("zip_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carte_vitale", models.IntegerField()),
                ("caisse_rattachement", models.IntegerField()),
                ("prescribing_doctor", models.CharField(max_length=300)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("photo_prescription", models.CharField(max_length=300)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nurse.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=300)),
                ("zip_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=300)),
                ("patients", models.ManyToManyField(to="nurse.Patient")),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
