# Generated by Django 3.2.5 on 2021-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0002_alter_nurse_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurse",
            name="patients",
            field=models.ManyToManyField(blank=True, to="nurse.Patient"),
        ),
    ]
