# Generated by Django 3.2.5 on 2022-07-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0004_auto_20210710_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="photo_prescription",
            field=models.ImageField(upload_to="prescriptions"),
        ),
    ]
