# Generated by Django 4.2.2 on 2023-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0005_alter_prescription_photo_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurse",
            name="address",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="nurse",
            name="city",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="nurse",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="nurse",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="patient",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
    ]
