# Generated by Django 4.2.3 on 2023-08-04 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0006_alter_nurse_address_alter_nurse_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="at_renew",
        ),
    ]
