# Generated by Django 4.2.3 on 2023-08-05 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0007_remove_prescription_at_renew"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="address",
            new_name="street",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="caisse_rattachement",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="carte_vitale",
        ),
        migrations.AddField(
            model_name="patient",
            name="birthday",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="caisse_rattachement",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="patient",
            name="health_card_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
