# Generated by Django 4.2.3 on 2023-08-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0008_rename_address_patient_street_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
