# Generated by Django 4.2.3 on 2023-08-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0009_alter_patient_birthday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="caisse_rattachement",
        ),
        migrations.AddField(
            model_name="patient",
            name="ss_provider_code",
            field=models.CharField(
                blank=True, help_text="code d'organisme de rattachement", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="health_card_number",
            field=models.CharField(blank=True, help_text="carte vitale", max_length=15),
        ),
    ]
