# Generated by Django 4.2.11 on 2024-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0011_useronesignalprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="email_doctor",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
