# Generated by Django 5.1.3 on 2024-11-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0014_stripeproduct_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
        migrations.AddField(
            model_name="subscription",
            name="amount_due",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(default="incomplete", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
