# Generated by Django 5.1.3 on 2024-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0015_remove_subscription_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
