# Generated by Django 5.1.3 on 2024-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0017_rename_amount_due_subscription_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payment_status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.BooleanField(default=False),
        ),
    ]
