# Generated by Django 5.1.3 on 2024-11-17 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0018_subscription_payment_status_alter_subscription_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerDetails",
            new_name="CustomerDetail",
        ),
    ]
