# Generated by Django 5.0.9 on 2024-11-03 18:40

from django.db import migrations

from main.migrations_helpers import enable_rls_on_all_models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(enable_rls_on_all_models),
    ]
