name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make virtualenv/test
      - run: make lint
      - run: make unittest
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make docker/build
